apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-balanced-sc
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: hyperdisk-balanced
  # Optional: Provision specific IOPS and Throughput at creation time
  provisioned-iops-on-create: "7000"
  provisioned-throughput-on-create: "250Mi"
