apiVersion: v2
name: gke-gen4-np-migrator
description: A Helm chart to distribute gke-gen4-np-migrator
type: application

version: 0.1.0
appVersion: "0.1.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
